# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Shift ID')),
                ('days_type', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday')], default='Sunday', verbose_name='Working day')),
                ('times_type', models.IntegerField(choices=[(0, 'Morning'), (1, 'Afternoon'), (2, 'Night'), (3, 'Off'), (4, 'General')], default='Morning', verbose_name='Shift')),
                ('comment', models.CharField(default='', max_length=255, verbose_name='Comment')),
            ],
        ),
    ]
