# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('worker_name', models.CharField(default='empty', max_length=200, verbose_name='Name')),
                ('days_type', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], default='Sunday', verbose_name='Working day')),
                ('times_type', models.IntegerField(choices=[(0, 'Morning'), (1, 'Afternoon'), (2, 'Night'), (3, 'Off'), (4, 'General')], default='Morning', verbose_name='Shift')),
                ('comment', models.CharField(default='', max_length=255, verbose_name='Comment')),
            ],
        ),
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
