# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Room Number')),
                ('floor', models.IntegerField(verbose_name='Room Floor')),
                ('room_size', models.IntegerField(verbose_name='Room Size (Square Meter)')),
                ('bathroom_size', models.IntegerField(verbose_name='Bathroom Size (Square Meter)')),
                ('double_beds_count', models.IntegerField(default=1, verbose_name='Double Beds Count')),
                ('single_beds_count', models.IntegerField(default=0, verbose_name='Single Beds Count')),
                ('bathroom_type', models.IntegerField(choices=[('BH', 'Bathtub'), ('SH', 'Shower')], default='Shower', verbose_name='Bathroom Type')),
                ('is_suite', models.BooleanField(default=False, verbose_name='Suite')),
                ('is_seaview', models.BooleanField(default=False, verbose_name='Sea View')),
                ('is_place_for_crib', models.BooleanField(default=True, verbose_name='Has Place For Crib')),
            ],
        ),
    ]
