# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkYamManagerApp', '0002_auto_20170521_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='clean_comment',
            field=models.CharField(default='', max_length=1000, verbose_name='Clean_comment'),
        ),
    ]
