# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ParkYamManagerApp', '0003_room_clean_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='', verbose_name='Message')),
                ('reply', models.TextField(default='', verbose_name='Reply')),
                ('replier_name', models.CharField(default='', max_length=255, verbose_name='Replier')),
                ('message_time', models.DateTimeField(auto_now=True, verbose_name='Message Time')),
                ('reply_time', models.DateTimeField(auto_now=True, verbose_name='Reply Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
