# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParkYamManagerApp', '0005_auto_20170606_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': (('can_send', 'Can send message'), ('can_reply', 'Can reply message'))},
        ),
    ]
