# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParkYamManagerApp', '0006_auto_20170606_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': (('can_send_message', 'Can send message'), ('can_reply_message', 'Can reply message'))},
        ),
    ]
