# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkYamManagerApp', '0007_auto_20170606_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='maintenance_comment',
            field=models.CharField(default='', max_length=1000, verbose_name='MaintenanceComment'),
        ),
        migrations.AddField(
            model_name='room',
            name='needs_maintenance',
            field=models.BooleanField(default=False, verbose_name='NeedsMaintenance'),
        ),
    ]
