# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParkYamManagerApp', '0008_auto_20170609_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': (('maintain_room', 'Can maintain room'),)},
        ),
    ]
