# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkYamManagerApp', '0010_room_is_room_being_cleaned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('worker_name', models.CharField(default='Type your name in here', max_length=255, verbose_name='Name')),
                ('sunday', models.IntegerField(choices=[(0, 'OFF_Morning'), (1, 'OFF_Afternoon'), (2, 'OFF_Night'), (3, 'Off_ALL_DAY'), (4, 'Off_Morning_Afternoon'), (5, 'Off_AftNoon_Night'), (6, 'Off_Morning_Night'), (7, 'General')], default='7', verbose_name='Sunday')),
                ('monday', models.IntegerField(choices=[(0, 'OFF_Morning'), (1, 'OFF_Afternoon'), (2, 'OFF_Night'), (3, 'Off_ALL_DAY'), (4, 'Off_Morning_Afternoon'), (5, 'Off_AftNoon_Night'), (6, 'Off_Morning_Night'), (7, 'General')], default='7', verbose_name='Monday')),
                ('tuesday', models.IntegerField(choices=[(0, 'OFF_Morning'), (1, 'OFF_Afternoon'), (2, 'OFF_Night'), (3, 'Off_ALL_DAY'), (4, 'Off_Morning_Afternoon'), (5, 'Off_AftNoon_Night'), (6, 'Off_Morning_Night'), (7, 'General')], default='7', verbose_name='Tuesday')),
                ('wednesday', models.IntegerField(choices=[(0, 'OFF_Morning'), (1, 'OFF_Afternoon'), (2, 'OFF_Night'), (3, 'Off_ALL_DAY'), (4, 'Off_Morning_Afternoon'), (5, 'Off_AftNoon_Night'), (6, 'Off_Morning_Night'), (7, 'General')], default='7', verbose_name='Wednesday')),
                ('thursday', models.IntegerField(choices=[(0, 'OFF_Morning'), (1, 'OFF_Afternoon'), (2, 'OFF_Night'), (3, 'Off_ALL_DAY'), (4, 'Off_Morning_Afternoon'), (5, 'Off_AftNoon_Night'), (6, 'Off_Morning_Night'), (7, 'General')], default='7', verbose_name='Thursday')),
                ('friday', models.IntegerField(choices=[(0, 'OFF_Morning'), (1, 'OFF_Afternoon'), (2, 'OFF_Night'), (3, 'Off_ALL_DAY'), (4, 'Off_Morning_Afternoon'), (5, 'Off_AftNoon_Night'), (6, 'Off_Morning_Night'), (7, 'General')], default='7', verbose_name='Friday')),
                ('saturday', models.IntegerField(choices=[(0, 'OFF_Morning'), (1, 'OFF_Afternoon'), (2, 'OFF_Night'), (3, 'Off_ALL_DAY'), (4, 'Off_Morning_Afternoon'), (5, 'Off_AftNoon_Night'), (6, 'Off_Morning_Night'), (7, 'General')], default='7', verbose_name='Saturday')),
                ('comment', models.CharField(default='Type here any comments', max_length=255, verbose_name='Comment')),
            ],
        ),
    ]
