# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkYamManagerApp', '0011_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionWorker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('worker_name', models.CharField(default='worker name', max_length=255, verbose_name='Name')),
            ],
        ),
    ]
