# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParkYamManagerApp', '0012_receptionworker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': (('maintain_room', 'Can maintain room'), ('clean_room', 'Can clean room'), ('view_room_status', 'Can view room status'))},
        ),
    ]
